In [1]:
import numpy as np

## Numpy Arrays / NDArrays Creation

In [2]:
l = [1,'a', [5,6,7]]
l

[1, 'a', [5, 6, 7]]

In [3]:
type(l)

list

In [4]:
b = np.array([5,6,7])
b

array([5, 6, 7])

In [5]:
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
d = np.ones((1,4))
d

array([[1., 1., 1., 1.]])

In [7]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
f = np.arange(5,11)
f

array([ 5,  6,  7,  8,  9, 10])

In [9]:
g = np.arange(2,21,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
h = np.arange(1,14,2)
h

array([ 1,  3,  5,  7,  9, 11, 13])

In [11]:
i = np.random.rand(5)
i

array([0.94896272, 0.52223929, 0.83069305, 0.89052799, 0.77544506])

In [12]:
j = np.random.randint(10,100, size=7)
j

array([54, 21, 87, 44, 64, 96, 41], dtype=int32)

## Properties

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a.size

5

In [15]:
a.shape

(5,)

In [16]:
b = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b.size

9

In [18]:
b.shape

(3, 3)

In [19]:
c = np.array( [ [1,2,3], [4,5,6] ] )
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c.shape

(2, 3)

In [21]:
d = np.array([1.1,2.2,3.3])
d

array([1.1, 2.2, 3.3])

In [22]:
d.dtype

dtype('float64')

In [23]:
c.dtype

dtype('int64')

In [24]:
x = np.random.randint(1,20,8)
x

array([17, 19,  3,  2, 15, 15, 12,  7], dtype=int32)

In [25]:
x.shape

(8,)

In [26]:
x.resize(2,4)

In [27]:
x

array([[17, 19,  3,  2],
       [15, 15, 12,  7]], dtype=int32)

In [28]:
x.resize(4,2)

In [29]:
x

array([[17, 19],
       [ 3,  2],
       [15, 15],
       [12,  7]], dtype=int32)

In [30]:
x.T

array([[17,  3, 15, 12],
       [19,  2, 15,  7]], dtype=int32)

In [31]:
x[-2,-2]

np.int32(15)

In [32]:
l = [2,6,9,1,4]
l

[2, 6, 9, 1, 4]

In [33]:
l[:]

[2, 6, 9, 1, 4]

In [34]:
l[2:]

[9, 1, 4]

In [35]:
l[:4]

[2, 6, 9, 1]

In [36]:
l[1:4]

[6, 9, 1]

In [37]:
x

array([[17, 19],
       [ 3,  2],
       [15, 15],
       [12,  7]], dtype=int32)

In [38]:
x[0:4][0:1]

array([[17, 19]], dtype=int32)

In [39]:
x.shape

(4, 2)

In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [41]:
a+b

array([5, 7, 9])

In [42]:
a-b

array([-3, -3, -3])

In [43]:
a*b

array([ 4, 10, 18])

In [44]:
a/b

array([0.25, 0.4 , 0.5 ])

In [45]:
a//b

array([0, 0, 0])

In [46]:
a%b

array([1, 2, 3])

In [47]:
a

array([1, 2, 3])

In [48]:
a.sum()

np.int64(6)

In [49]:
a.min()

np.int64(1)

In [50]:
a.max()

np.int64(3)

In [51]:
a.mean()

np.float64(2.0)

In [52]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.sum(b, axis=0)

array([5, 7, 9])

In [54]:
np.sum(b, axis=1)

array([ 6, 15])

In [55]:
np.min(b, axis=0)

array([1, 2, 3])

In [56]:
np.min(b, axis=1)

array([1, 4])

## Boolean Arrays

In [57]:
x = np.random.randint(1,50,15)
x

array([35, 45, 16, 14,  1, 21, 17,  7,  1, 47, 24, 14, 28, 43, 26],
      dtype=int32)

In [58]:
x.resize(3,5)
x

array([[35, 45, 16, 14,  1],
       [21, 17,  7,  1, 47],
       [24, 14, 28, 43, 26]], dtype=int32)

In [59]:
barr = (x > 20)
barr

array([[ True,  True, False, False, False],
       [ True, False, False, False,  True],
       [ True, False,  True,  True,  True]])

In [60]:
x[barr]

array([35, 45, 21, 47, 24, 28, 43, 26], dtype=int32)

In [61]:
x[~barr]

array([16, 14,  1, 17,  7,  1, 14], dtype=int32)

In [62]:
age = np.random.randint(1,21,25)
age.resize(5,5)
age

array([[15, 19, 11, 18, 16],
       [14, 17, 14, 19,  4],
       [12, 17,  5,  9, 13],
       [12, 15, 13, 13,  4],
       [15, 11, 12, 10,  6]], dtype=int32)

In [63]:
ageb = (age > 18)
ageb

array([[False,  True, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [64]:
age[ageb]

array([19, 19], dtype=int32)

In [65]:
age[~ageb]

array([15, 11, 18, 16, 14, 17, 14,  4, 12, 17,  5,  9, 13, 12, 15, 13, 13,
        4, 15, 11, 12, 10,  6], dtype=int32)

In [66]:
age[age > 18]

array([19, 19], dtype=int32)

In [67]:
zo = np.random.randint(0,2,25)
zo.resize(5,5)
zo

array([[1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [68]:
zo[zo == 1].size

12

In [69]:
zo[zo == 0].size

13

#### SYMBOLS -> &, |, ~

In [70]:
sample = np.random.randint(0,3,30)
sample.resize(3,10)
sample

array([[2, 1, 1, 2, 1, 1, 1, 2, 0, 2],
       [0, 1, 1, 0, 1, 2, 0, 2, 0, 2],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 1]], dtype=int32)

In [71]:
sample[ (sample == 2)    |     (sample == 0) ]

array([2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int32)

In [72]:
sample[     (sample > 0)           &         (sample < 2)      ]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

#### eq , ne, gt, gte, lt, lte

In [73]:
z = np.arange(1,11)
z.resize(5,2)
z

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [74]:
z.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
# Concatenation
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [76]:
p = np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [77]:
q = np.array([[5,6],[7,8]])
q

array([[5, 6],
       [7, 8]])

In [78]:
np.vstack((p,q))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
np.hstack((p,q))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [80]:
s = np.arange(1,10)
s.resize(3,3)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a = 1
b = 2

In [83]:
a

1

In [84]:
c = b
c

2

In [85]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
t = s
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
t[0][0] = 111
t

array([[111,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [88]:
s

array([[111,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [89]:
s[0][0] = 222
s

array([[222,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [90]:
t

array([[222,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [91]:
p = np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [92]:
c = p.copy()
c

array([[1, 2],
       [3, 4]])

In [93]:
c[0][0] = 100
c

array([[100,   2],
       [  3,   4]])

In [94]:
p

array([[1, 2],
       [3, 4]])

In [102]:
xy = np.random.randint(1,6,9)
xy.resize(3,3)
xy

array([[4, 5, 5],
       [2, 2, 3],
       [5, 2, 2]], dtype=int32)

In [103]:
ab = xy.copy()
np.sort(ab, axis=1)

array([[4, 5, 5],
       [2, 2, 3],
       [2, 2, 5]], dtype=int32)

In [104]:
cd = xy.copy()
np.sort(cd, axis=0)

array([[2, 2, 2],
       [4, 2, 3],
       [5, 5, 5]], dtype=int32)

In [105]:
np.unique(cd)

array([2, 3, 4, 5], dtype=int32)

In [106]:
cd[cd > 2]

array([4, 5, 5, 3, 5], dtype=int32)

In [108]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [110]:
# Matrix Operations
xx = np.random.randint(1,11,9)
xx.resize(3,3)
xx

array([[4, 1, 1],
       [1, 8, 6],
       [4, 7, 3]], dtype=int32)

In [111]:
yy = np.random.randint(1,11,9)
yy.resize(3,3)
yy

array([[ 2,  6,  2],
       [ 5,  2,  9],
       [ 8, 10,  2]], dtype=int32)

In [112]:
xx + yy

array([[ 6,  7,  3],
       [ 6, 10, 15],
       [12, 17,  5]], dtype=int32)

In [113]:
xx * yy # Hadamard Product

array([[ 8,  6,  2],
       [ 5, 16, 54],
       [32, 70,  6]], dtype=int32)

In [114]:
np.dot(xx,yy)

array([[21, 36, 19],
       [90, 82, 86],
       [67, 68, 77]], dtype=int32)

In [115]:
np.cross(xx,yy)

array([[ -4,  -6,  22],
       [ 60,  21, -38],
       [-16,  16, -16]], dtype=int32)

In [117]:
# 1
a = np.arange(1,21)
print(np.sum(a))

210


In [118]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [120]:
# 2
b = np.random.randint(1,11,9)
b.resize(3,3)
b

array([[ 5,  5, 10],
       [ 7,  4,  9],
       [10,  2,  8]], dtype=int32)

In [124]:
b[1]

array([7, 4, 9], dtype=int32)

In [126]:
print(b[ b%2 == 0 ])

[10  4 10  2  8]
