In [1]:
import numpy as np

## Numpy Arrays / NDArrays Creation

In [2]:
l = [1,'a', [5,6,7]]
l

[1, 'a', [5, 6, 7]]

In [3]:
type(l)

list

In [4]:
b = np.array([5,6,7])
b

array([5, 6, 7])

In [5]:
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
d = np.ones((1,4))
d

array([[1., 1., 1., 1.]])

In [7]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
f = np.arange(5,11)
f

array([ 5,  6,  7,  8,  9, 10])

In [9]:
g = np.arange(2,21,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
h = np.arange(1,14,2)
h

array([ 1,  3,  5,  7,  9, 11, 13])

In [11]:
i = np.random.rand(5)
i

array([0.56906748, 0.8416239 , 0.6701733 , 0.67126515, 0.62997753])

In [12]:
j = np.random.randint(10,100, size=7)
j

array([69, 67, 23, 52, 41, 66, 56], dtype=int32)

## Properties

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a.size

5

In [15]:
a.shape

(5,)

In [16]:
b = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b.size

9

In [18]:
b.shape

(3, 3)

In [19]:
c = np.array( [ [1,2,3], [4,5,6] ] )
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c.shape

(2, 3)

In [21]:
d = np.array([1.1,2.2,3.3])
d

array([1.1, 2.2, 3.3])

In [22]:
d.dtype

dtype('float64')

In [23]:
c.dtype

dtype('int64')

In [24]:
x = np.random.randint(1,20,8)
x

array([ 5, 17, 16, 11,  2, 19,  3, 14], dtype=int32)

In [25]:
x.shape

(8,)

In [26]:
x.resize(2,4)

In [27]:
x

array([[ 5, 17, 16, 11],
       [ 2, 19,  3, 14]], dtype=int32)

In [28]:
x.resize(4,2)

In [29]:
x

array([[ 5, 17],
       [16, 11],
       [ 2, 19],
       [ 3, 14]], dtype=int32)

In [30]:
x.T

array([[ 5, 16,  2,  3],
       [17, 11, 19, 14]], dtype=int32)

In [31]:
x[-2,-2]

np.int32(2)

In [32]:
l = [2,6,9,1,4]
l

[2, 6, 9, 1, 4]

In [33]:
l[:]

[2, 6, 9, 1, 4]

In [34]:
l[2:]

[9, 1, 4]

In [35]:
l[:4]

[2, 6, 9, 1]

In [36]:
l[1:4]

[6, 9, 1]

In [40]:
x

array([[ 5, 17],
       [16, 11],
       [ 2, 19],
       [ 3, 14]], dtype=int32)

In [51]:
x[0:4][0:1]

array([[ 5, 17]], dtype=int32)

In [39]:
x.shape

(4, 2)

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [53]:
a+b

array([5, 7, 9])

In [54]:
a-b

array([-3, -3, -3])

In [55]:
a*b

array([ 4, 10, 18])

In [56]:
a/b

array([0.25, 0.4 , 0.5 ])

In [57]:
a//b

array([0, 0, 0])

In [58]:
a%b

array([1, 2, 3])

In [59]:
a

array([1, 2, 3])

In [60]:
a.sum()

np.int64(6)

In [61]:
a.min()

np.int64(1)

In [62]:
a.max()

np.int64(3)

In [63]:
a.mean()

np.float64(2.0)

In [64]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.sum(b, axis=0)

array([5, 7, 9])

In [66]:
np.sum(b, axis=1)

array([ 6, 15])

In [67]:
np.min(b, axis=0)

array([1, 2, 3])

In [69]:
np.min(b, axis=1)

array([1, 4])

## Boolean Arrays

In [71]:
x = np.random.randint(1,50,15)
x

array([48, 32, 45, 45, 11, 21, 48, 11, 26, 17, 36, 27, 37, 27, 13],
      dtype=int32)

In [72]:
x.resize(3,5)
x

array([[48, 32, 45, 45, 11],
       [21, 48, 11, 26, 17],
       [36, 27, 37, 27, 13]], dtype=int32)

In [73]:
barr = (x > 20)
barr

array([[ True,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True, False]])

In [74]:
x[barr]

array([48, 32, 45, 45, 21, 48, 26, 36, 27, 37, 27], dtype=int32)

In [75]:
x[~barr]

array([11, 11, 17, 13], dtype=int32)

In [78]:
age = np.random.randint(1,21,25)
age.resize(5,5)
age

array([[14,  9,  6, 12,  7],
       [20,  5,  4, 19, 20],
       [19, 14, 12, 11, 17],
       [18,  1, 18, 12,  3],
       [14, 20, 13, 19, 16]], dtype=int32)

In [79]:
ageb = (age > 18)
ageb

array([[False, False, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False,  True, False]])

In [80]:
age[ageb]

array([20, 19, 20, 19, 20, 19], dtype=int32)

In [81]:
age[~ageb]

array([14,  9,  6, 12,  7,  5,  4, 14, 12, 11, 17, 18,  1, 18, 12,  3, 14,
       13, 16], dtype=int32)

In [82]:
age[age > 18]

array([20, 19, 20, 19, 20, 19], dtype=int32)

In [83]:
zo = np.random.randint(0,2,25)
zo.resize(5,5)
zo

array([[0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1]], dtype=int32)

In [86]:
zo[zo == 1].size

11

In [87]:
zo[zo == 0].size

14

#### SYMBOLS -> &, |, ~

In [88]:
sample = np.random.randint(0,3,30)
sample.resize(3,10)
sample

array([[2, 1, 1, 0, 2, 1, 2, 2, 0, 1],
       [1, 2, 1, 0, 0, 2, 1, 2, 2, 1],
       [0, 1, 0, 1, 2, 0, 0, 2, 0, 2]], dtype=int32)

In [89]:
sample[ (sample == 2)    |     (sample == 0) ]

array([2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2],
      dtype=int32)

In [90]:
sample[     (sample > 0)           &         (sample < 2)      ]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

#### eq , ne, gt, gte, lt, lte